# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincode',
            name='name',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='skincode',
            name='code',
            field=models.CharField(default='', max_length=63),
        ),
    ]
